"""
Django settings for botapi project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE_DIR = BASE_DIR + '/cache'
QR_FILE = CACHE_DIR + '/qr/qr.png'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o03&)3kjwu+59stnrbq@7%)(+b@dzvf8z3s^996z^5v12@xu6q'

BOT_NAME = 'XiaoBei-Bot'

#INTER_API_KEY = 'iKSTzlTOGBRz7VfhmPHhUEsL'
#INTER_SECRET_KEY = 'ISAs2EKIsHf6Y1swqRR0Iu1I4nFr3GWB'

#OHS

INTER_API_KEY = 'c1AgtG7vwSNlDGpCNgsP5wwF'
INTER_SECRET_KEY = '7fHURX6iqjCvAMYaO2rxNZNNPyDdANI1'

PHOTO_API_KEY = '2iAW4mnRdGP7c9nXL5cqOduY'
PHOTO_SECRET_KEY = '1BXPvOea2F0nnCd55rlX0DL7GnHLDGYw'

SKILL_IDS = ['61626', '62327']
#SERVICE_ID = 'S19352'
SERVICE_ID = 'S19329'

INTERACTION_URL = 'https://aip.baidubce.com/rpc/2.0/unit/service/chat?access_token='
DISTINGUISH_URL = 'https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic?access_token='

QR_TIMEOUT = 10

PUB_TOKEN = 'xiaobei777'
PUB_ID = 'wx0154d92f9e860e70'
PUB_SECRET = 'wx0154d92f9e860e70'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'bot.apps.BotConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL=True

ROOT_URLCONF = 'botapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'botapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/bot_api/static/'
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), )
STATIC_ROOT = (os.path.join(BASE_DIR, 'static'))
